### ISSUE TITLE
vCenter Simulator Docker Container: unit vs integration testing

### ISSUE THREAD

**Issue by lucdekens** [brianbunke/brianbunke.github.io#5]
Hi Brian,
Nice post, just one question.
In the closing paragraph you announce your next post, which I'm definitely looking forward to.
But shouldn't that say 'integration test' instead of 'unit test'?

**Comment by brianbunke** [comment]
Indeed it should. I've spent so much time thinking about unit tests in PowerCLI land, I wrote the wrong thing in auto-pilot mode. Fixed in [e9b9373](https://github.com/brianbunke/brianbunke.github.io/commit/e9b937315dac40f73ebc0b251e2234413ce59227).

Thanks, Luc, and enjoy your awesome-sounding 2019!
